"""add_reasoning_to_tailored_resumes

Revision ID: 2e04c11fa680
Revises: 800ba8f943f1
Create Date: 2026-05-11 01:15:14.821765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e04c11fa680'
down_revision: Union[str, None] = '800ba8f943f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tailored_resumes', sa.Column('reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tailored_resumes', 'reasoning')
    # ### end Alembic commands ###
