"""create_resume_bullets_and_tailored_resumes

Revision ID: 800ba8f943f1
Revises: ace8f914132e
Create Date: 2026-05-10 06:58:37.373865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '800ba8f943f1'
down_revision: Union[str, None] = 'ace8f914132e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_bullets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tailored_resumes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('original_bullets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tailored_bullets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tailored_resumes')
    op.drop_table('resume_bullets')
    # ### end Alembic commands ###
